version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: didimlog-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: didimlog
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:alpine
    container_name: didimlog-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
