services:
  didim-log-be:
    image: stdiodh/didim-log-be:latest
    container_name: didim-log-be-container
    ports:
      - "8083:8080"
    env_file:
      - /home/ec2-user/app/didim-log-be/.env
    networks:
      - didim-log-network
    restart: always
    depends_on:
      - mongo
      - redis

  # 2. MongoDB
  mongo:
    image: mongo:latest
    container_name: didim-log-be-mongodb-container
    restart: always
    volumes:
      - mongodb-data:/data/db
    networks:
      - didim-log-network

  # 3. Redis
  redis:
    image: redis:alpine
    container_name: didim-log-be-redis-container
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - didim-log-network

networks:
  didim-log-network:
    driver: bridge

volumes:
  mongodb-data:
  redis-data:
